### ISSUE TITLE
Mismatching function prototypes in ModelicaInternal.[ch]

### ISSUE THREAD

**Issue by d94pn** [modelica/ModelicaStandardLibrary#2843]
Several function implementations in ModelicaInternal.c hardcodes _Ret_z_:

_Ret_z_ const char* ModelicaInternal_fullPathName(_In_z_ const char* name)
_Ret_z_ const char* ModelicaInternal_temporaryFileName(void)
_Ret_z_ const char* ModelicaInternal_readLine(_In_z_ const char* fileName,
                                      int lineNumber, _Out_ int* endOfFile)
_Ret_z_ const char* ModelicaInternal_getcwd(int dummy)

while the declarations in ModelicaInternal.c does not:

MODELICA_EXPORT MODELICA_RETURNNONNULLATTR const char* ModelicaInternal_fullPathName(
    _In_z_ const char* name) MODELICA_NONNULLATTR;
...etc

**Comment by beutlich** [comment]
This is by design since these four functions are the only functions returning a character pointer. As far as I figured it out, the `__attribute__((returns_nonnull))` must only be be present in the function declaration and not in the function definition, however the SAL annotations generally should be used in both declaration and definition.
