### ISSUE TITLE
Is InitPID.DoNotUse_InitialIntegratorState still needed?

### ISSUE THREAD

**Issue by beutlich** [modelica/ModelicaStandardLibrary#2892]
For MSL 4.0.0, can we remove the PID initialization type [InitPID](https://doc.modelica.org/Modelica%203.2.3/Resources/helpDymola/Modelica_Blocks_Types.html#Modelica.Blocks.Types.InitPID) with the Modelica 2.2 compatible initialization alternative `DoNotUse_InitialIntegratorState`? Or is it still needed?

**Comment by beutlich** [comment]
See also #1215. Seems we never can get rid of our legacy.

**Comment by dietmarw** [comment]
I'd argue that if there is a broken issue that can not be solved neither in a backward compatible way nor by conversion then we simply need to decide to either live with it forever or fix it in a breaking way. For the latter the MSL 4.0.0 would be the right time. Otherwise it will have to live in the MSL for another 10 years at least which seems not appropriate.

**Comment by MartinOtter** [comment]
Fine for me to remove option DoNotUse_InitialIntegratorState for MSL 4.0.0, even if it is not possible to provide a conversion script.
