### ISSUE TITLE
Wrong position of fire input in GTO

### ISSUE THREAD

**Issue by max-privato** [modelica/ModelicaStandardLibrary#3165]
The GTO fire input should be placed in contact or very near the actual gate wire. The present switch, instead, has the fuchsia fire input too far from the gate blue indicator: see the image below.

<img width="1152" alt="Immagine" src="https://user-images.githubusercontent.com/37046832/67302172-c66ef680-f4f0-11e9-8343-e0c67434970f.png">

**Comment by dietmarw** [comment]
Just as a comment this position was probably chosen by design. Also present in `IdealThyristor`. 
Other components that have a firing signal (e.g., `SimpleTriac`) also route it to the corner. Though they draw also a connection line on the icon. So I would be careful calling this "wrong" but rather discuss if it should be improved or not.

**Comment by max-privato** [comment]
I totally agree with @dietmarw position.

I opened this ticket not because I thought something was wrong with the symbol.
Instead, I just evaluated the actual effectiveness of the diagrams.
Consider for instance the following diagram: I think that a connection of the fuchsia line to the gate would surely significantly enhance the diagram appearance and quality.
If we don't want to modify the position of the fuchsia arrow, we could just add a connection line.

![image](https://user-images.githubusercontent.com/37046832/67313798-e4922200-f503-11e9-9ab7-eb2460dde5cc.png)

**Comment by dietmarw** [comment]
What I could think of is adding a dashed line so these would look like:
![image](https://user-images.githubusercontent.com/9332/67369522-70926100-f579-11e9-845e-23627e9d7818.png)
Without changing  the position of the connector.
What do you think?

**Comment by dietmarw** [comment]
One thing I *did* notice is that the symbol of the thyristor is actually that of a GTO, i.e. the bar across should not be there. Here is what I would change the symbols to so that they actually are more correct and clean:
![image](https://user-images.githubusercontent.com/9332/67370860-bf40fa80-f57b-11e9-8dd1-f518141cc324.png)
Again, what do you think?

**Comment by max-privato** [comment]
I agree with both your proposals: the connecting lines for thyristor and GTO form me are ok.
I also agree that the thyristor symbol with the bar across is that of a GTO and therefore should be corrected.

**Comment by dietmarw** [comment]
PR created that changes the design to the following:
![image](https://user-images.githubusercontent.com/9332/67384289-2f0db000-f591-11e9-80a5-0c35f3b5ef8e.png)
