### ISSUE TITLE
LeakageWithCoefficient should have a port for reluctance input

### ISSUE THREAD

**Issue by JoeRiel** [modelica/ModelicaStandardLibrary#3300]
The model Modelica.Magnetic.FluxTubes.Basic.LeakageWithCoefficient has an input signal, R_mUsefulTot, that provides the total reluctance of the path in which it is connected. To make this part usable in a GUI, that input should be a port to which a real signal can be connected. 

Actually, it's not clear to me why this quantity is an input and not a parameter. Are there examples of a model where it varies?  The doc-string for the component ("... not for dynamic simulation of actuators") suggests it isn't intended to be used in that application.

**Comment by AHaumer** [comment]
I'm not sure whether `input` should be a `parameter`, I'll ask the authors about their intentions. 
"... not for dynamic simulation of actuators": Please read the full doc, the authors wrote:
" ...This would generate a reluctance force in the leakage element that is not accounted for properly."
I interpret this thay way that if you don'ct care about the reluctance force you can use this leakage element in parallel to the "usefull" element, assuming that the coupling coefficient remains constant which in turns leads to a change of the leakage reluctance if "usefull" reluctanec changes. 
Following the idea, `R_mUsefulTot` should be an input rather than a parameter.

**Comment by AHaumer** [comment]
I've created a PR, showing the usage in the Example `BasicExamples.QuadraticCoreAirgap`

**Comment by christiankral** [comment]
Re-open due to https://github.com/modelica/ModelicaStandardLibrary/pull/3424#issuecomment-586562266

**Comment by dietmarw** [comment]
Fixed again by #3424

**Comment by dietmarw** [comment]
Probably wait for #3431 first...
