### ISSUE TITLE
Strange use of Modelica.Constants.inf in Modelica.Fluid.Examples.Explanatory.MomentumBalanceFittings

### ISSUE THREAD

**Issue by carlj-w** [modelica/ModelicaStandardLibrary#3390]
`Modelica.Fluid.Examples.Explanatory.MomentumBalanceFittings` and `ModelicaTest.Fluid.TestComponents.Fittings.TestSuddenExpansion` (these two seem to be the same model) use `Modelica.Constants.inf` for the parameter `diameter_b` in the components `leftAdapter` and `rightAdapter`.

From what I can see, the only way this could work is if you are running with a mis-configured `ModelicaServices.Machine.inf` (since `Modelica.Constants.inf` is set to `ModelicaServices.Machine.inf`). The description for these constants are (same for both):

> "Biggest Real number such that inf and -inf are representable on the machine"

and if you run these models with a proper value for `ModelicaServices.Machine.inf`, the calculations using the `diameter_b` parameter would produce actual floating point INFs and the simulation would fail.

I am guessing that the models were made using a basic, non-configured, ModelicaServices, where inf is set to 1e60, so I propose that the `diameter_b` parameter values are changed to that explicit value.

**Comment by HansOlsson** [comment]
I agree, and I think this is the best solution.

And to clarify - the problem is that formulas contain `diameter_b^2` and also multiplications with some minor factors. Thus if we want to use `Modelica.Constants.inf` we would need to use `sqrt(Modelica.Constants.inf)/...` or `Modelica.Constants.inf^(1/3)`, both of which seem messier.

Problems due to the bad "default" values for these numeric constants was also a problem in #3357 ; and the descriptions aren't that good either as noted in #2056 .
