### ISSUE TITLE
No build project for ModelicaExternalC

### ISSUE THREAD

**Issue by HansOlsson** [modelica/ModelicaStandardLibrary#3484]
There is no VisualStudio project for ModelicaExternalC.

This is **not blocking** for MSL 4.0.0, since tool vendors are anyway responsible for those libraries.

For any tool that has existing build projects, note that they might need an update due to #2994 (for Dymola 2020x  see also https://github.com/modelica/ModelicaStandardLibrary/pull/3453#issuecomment-592506380_ ).

**Comment by beutlich** [comment]
There cannot be a generic build project due to tool-specific implementations of ModelicaServices.ExternalReferences.loadResource and the ModelicaUtilities. Therefore, I believe, both build and distribution of ModelicaExternalC .{dll, lib, so, a, etc} is in the tool-vendor's repsonsibility.

**Comment by HansOlsson** [comment]
Ok, makes sense.

**Comment by sjoelund** [comment]
The ModelicaUtilities is totally separate and of course the tool's responsibility. But ModelicaExternalC can be compiled in a mostly tool-neutral way (provided you use the same OS and/or compilers). There is nothing special in `../../C-Sources/ModelicaFFT.c ../../C-Sources/ModelicaInternal.c ../../C-Sources/ModelicaRandom.c ../../C-Sources/ModelicaStrings.c`; the tables is perhaps the trickiest one (due to `usertab`).
