### ISSUE TITLE
Dead Modelica URI link in documentation

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaStandardLibrary#3937]
A dae link like this causes problems for those that try to keep their documentation free of dead links:
https://github.com/modelica/ModelicaStandardLibrary/blob/8345852d3b7d8af752cd4960e4dff5a935ba8f3b/Modelica/Electrical/Machines/Thermal/package.mo#L140

This is the only case I'm aware of.  Any chance we could avoid pointing to non-existing classes like this?

**Comment by dietmarw** [comment]
I agree that including links to future planned implementation (or just mentioning them) is a bad idea since it creates a false expectation which (as shown in the past of MSL) often could not be satisfied in the end. 

In addition, the "dead" link you pointed uncovers a slightly larger mistake of not having correctly removed (outcommented) the following text section that belongs to the defunct h5 heading. I'm going to create a PR to get rid of the whole superfluous section.
