### ISSUE TITLE
Documentation image M_OLine error

### ISSUE THREAD

**Issue by paultjevdh** [modelica/ModelicaStandardLibrary#3960]
Hello,
It seems the documentation image at modelica://Modelica/Resources/Images/Electrical/Analog/segment.png has some errors.
The component subscripts should indicate the lines between which the component is connected. 
In the image C41 is however connected in parallel to C42. C42 should be connected between nets n4 and n2 instead of n4 and n1.
Also C31 is connected to n2 rather than n1.
Finally G31 is connected to n2 instead of n1.
![segment](https://user-images.githubusercontent.com/59084059/158250070-2c5bd23e-a50d-4487-ad1b-3e8aeb3b7bc6.png)

A proposal for the fixed image is below:
![segment](https://user-images.githubusercontent.com/59084059/158250168-ba7f48db-0c60-4f86-a05e-9b9f52c083be.png)

Best regards,
Paul van der Hulst

**Comment by dietmarw** [comment]
It looks like these old versions of the images were forgotten to get removed when #3748 was fixed by #3756 and  #3815. 
The new versions can be found in `Modelica/Resources/Modelica/Resources/Images/Electrical/Analog/Lines/segment.png` and `Modelica/Resources/Modelica/Resources/Images/Electrical/Analog/Lines/segment_last.png`, they are used in the documentation of: `Modelica.Electrical.Analog.Lines.M_OLine`.

@max-privato and @AHaumer, do you agree that the old versions: 
 - `Modelica/Resources/Modelica/Resources/Images/Electrical/Analog/segment.png`
 - `Modelica/Resources/Modelica/Resources/Images/Electrical/Analog/segment_last.png`
 - `Modelica/Resources/Modelica/Resources/Images/Electrical/Analog/segment_first.png`
can be safely removed since they are not used anywhere in the MSL any more?

**Comment by paultjevdh** [comment]
Hi,
You're completely correct. I missed that this was fixed in the current development code.
This leaves me with the question when 4.1 is due...

Best regards,
Paul

**Comment by dietmarw** [comment]
@paultjevdh  Unfortunately there is currently no timeline available. The good new is that the current development version can be used directly in your tool given that your tool has been set up for MSL 4.0.0.

**Comment by max-privato** [comment]
> It looks like these old versions of the images were forgotten to get removed when #3748 was fixed by #3756 and #3815. The new versions can be found in `Modelica/Resources/Modelica/Resources/Images/Electrical/Analog/Lines/segment.png` and `Modelica/Resources/Modelica/Resources/Images/Electrical/Analog/Lines/segment_last.png`, they are used in the documentation of: `Modelica.Electrical.Analog.Lines.M_OLine`.
> 
> @max-privato and @AHaumer, do you agree that the old versions:
> 
> * `Modelica/Resources/Modelica/Resources/Images/Electrical/Analog/segment.png`
> * `Modelica/Resources/Modelica/Resources/Images/Electrical/Analog/segment_last.png`
> * `Modelica/Resources/Modelica/Resources/Images/Electrical/Analog/segment_first.png`
>   can be safely removed since they are not used anywhere in the MSL any more?

Agree. they are bad, never used and created portential misunderstandings.
BTW I like much more the new pictures that I mysself  created :-)

**Comment by paultjevdh** [comment]
I agree, much better. Thanks!
