### ISSUE TITLE
Modelica.StateGraph.Examples.Utilities.Tank could set units for its variables.

### ISSUE THREAD

**Issue by qlambert-pro** [modelica/ModelicaStandardLibrary#4076]
In particular:

```
  Real level(start = 0, fixed = true, unit = "1") "Tank level in % of max height";
  parameter Real A(unit = "m2") = 1 "Ground area of tank in m^2";
  parameter Real a(unit = "m2") = 0.2 "Area of drain hole in m^2";
  parameter Real hmax(unit = "m") = 1 "Max height of tank in m";
  ```

**Comment by beutlich** [comment]
I would not add the unit in the desciption comment `... in m^2` since the user can change the display unit as desired.

**Comment by henrikt-ma** [comment]
> I would not add the unit in the description comment `... in m^2` since the user can change the display unit as desired.

Right.  Not because the statement would technically be wrong if interpreted as applying to the `unit`, but both because of the confusion it may causes in the presence of `displayUnit` and because of the not-so-good-looking redundancy when the description is displayed in a contexts where the parameter value is already displayed with the unit.

**Comment by henrikt-ma** [comment]
> I would not add the unit in the description comment `... in m^2` since the user can change the display unit as desired.

This is a pattern that should be fixed more generally in the entire library.  The regexp ` in [a-zA-Z0-9^/.]*"` gives lots of examples (but also meny matches which have nothing to do with redundant units).
