### ISSUE TITLE
WallConstProps 

### ISSUE THREAD

**Issue by achniouel** [modelica/ModelicaStandardLibrary#4218]
Greetings everyone,

As a newcomer, I'm facing an issue while attempting to make changes to WallConstProps to introduce temperature-dependent material properties for walls. My questions are as follows:

I attempted to create a new model by duplicating the WallConstProps code and making modifications, but I encountered an error: "SI.Temperature not found in scope WallConstProps." This error occurred even when I didn't make any changes to the code. Does anyone have any insights into why this is happening, or is there another wall model that accounts for material property dependencies on temperature?

I appreciate your assistance. Thank you.

**Comment by HansOlsson** [comment]
This seems like a question for stackoverflow - not for the repo.

However:
- Use `Modelica.Units.SI.Temperature` instead of `SI.Temperature`; the reason is that `Modelica.Fluid` contains `import Modelica.Units.SI;import Cv = Modelica.Units.Conversions;`. (Tools should handle that when copying a class.)
- A model for a temperature-dependent material may be more complicated.
