### ISSUE TITLE
Move `Rn` and `Rp` models into the `Utilities` package

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaStandardLibrary#576]
**Reported by dietmarw on 27 Jun 2011 08:25 UTC**
Currently the example model `Modelica.Electrical.Analog.Examples.CauerLowPassSC` contains two submodels 
 * `Rn`
 * `Rp`

It's confusing for some users that a model can contain other models. when normally packages are used for this purpose. Since `Modelica.Electrical.Analog.Examples` already contains a `Utilities` subpackage I would recommend moving those two models `Rn` and `Rp` into the sub-package `Modelica.Electrical.Analog.Examples.CauerLowPassSC.Utilities` for the next non-backward compatible version of MSL and provide the proper conversion script.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/576

**Comment by modelica-trac-importer** [comment]
**Comment by dietmarw on 1 Aug 2015 21:36 UTC**
Milestone renamed

**Comment by modelica-trac-importer** [comment]
**Comment by dietmarw on 1 Aug 2015 21:39 UTC**
Milestone renamed

**Comment by kristinmajetta** [comment]
It might be confusing (which I doubt), but it also could help to show the users the wide range of possibilities they have when creating a model. Therefore I would prefer to not move the submodels into a sub-package. Or is it a guideline of MSL?

**Comment by dietmarw** [comment]
Models within models are always confusing. Especially since we teach people to put models into packages not into models. MSL being a role model here should not really advertise this.

**Comment by HansOlsson** [comment]
If they are models within models instead of models in packages they cannot be used anywhere else.

I don't know if it makes sense to re-use these models in other contexts - but I think that could influence the decision on whether to move them: either encourage reuse by having them in Utilities - or prevent misuse by keeping them local to the model.

**Comment by dietmarw** [comment]
My suggestion is to make an improved version by creating **one** component that is called `SwitchedCapacitor` and place that under `Utilities`. This new `SwitchedCapacitor` can then be used instead of `Rp` and `Rn` but accept a resistance value that can be negative and will hence change the nature of the `SwitchedCapacitor` from positive to negative resistance. This can also fix the connectors which are kind of wrong because they use "n" for both sides.

![image](https://user-images.githubusercontent.com/9332/39590663-dfe3647a-4f01-11e8-94c9-bb196b2f9ea4.png)
